name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Deno
        uses: denoland/setup-deno@v1

      - name: Format
        run: deno fmt --check

      - name: Check
        run: deno check --remote mod.ts

      - name: Lint
        run: deno lint

      - name: Tests
        run: deno test

  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        if: |
          startsWith(github.repository, 'voorjaar') && 
          startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true

      - name: Deploy
        uses: denoland/deployctl@v1
        with:
          project: "fresh-mtos"
          entrypoint: "./example/main.ts"
